name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  |
        sudo docker stop react-docker || true
        sudo docker rm react-docker || true
        sudo docker build -t react-docker .
        sudo docker run -d --name react-docker -p 80:5173 react-docker
        sudo docker image prune -f
